index.html
added bootstrap link and dropdown menu. pull the branch(or gitclone) and test on live server.
=> added cuisine dropwdown

recipe-detail-page.html
Added html file for recipe detail page and added basic html template
=> Added Recipe Details Page html file

assets/css/style.css, assets/js/script.js, index.html
it should switch between light and dark mode
=> 3 add lightdark mode functionality ensure it persists across all pages

.github/PULL_REQUEST_TEMPLATE.md
Added the PR template in a new folder for us to write our info when pushing to the main
=> added the folder github and a PR template

recipe-detail-page.html
Added back button on right side that takes you back to main page 
added title
=> 9 create back button for the recipe detail page

assets/css/style.css, assets/js/script.js, recipecards.html
This solves the issue of a static recipe card. Now it is dynamic and responsive to the API.
Fixes #[issue]
script.js
recipecards.html
=> 24 create responsive recipe cards to the api

assets/css/style.css, assets/js/script.js, index.html, recipecards.html
Added Button Coloring without the !important tag
Fixes #5 
- index.html
=> modified the buttons

assets/css/style.css, index.html, recipecards.html, recipedetails.html
The code for the other pages wasn't working well because I hadn't added the theme to the other pages, so I added that, and I also changed the name to Theme to make it look cleaner. I also gave it width and height because it was bigger than I thought it needed to be.
Fixes #44 
-index.html
- clone the branch using git checkout and the branch name
=> 44 add the light and dark mode to all pages

assets/js/script.js
Implementation of logging the recipe id when you click on a recipe card so that the recipe ID pops up on the third page.
Fixes #39 
javascript
=> added recipe id when you click on one recipe

assets/css/style.css, index.html
I fixed the bug where, when you clicked on the theme button, it went back to the default blue of Bootstrap instead of staying our navy blue color. I added an id to the submit button, and I targeted the id of the theme button instead of the classes. I also targeted the id to use hover, so it shows it highlighted. 
Fixes #37 
- index.html …
=> 37 check for the bug for the hover in light and dark mode and submit

assets/css/style.css, assets/js/script.js, recipecards.html
Our "view recipe" btn on each recipe card was proportionate to the elements as opposed to universal. Now it is the same on each card.
the code changes are the  css doc(lines 181 to 210)
=> fixed the view recipe card to be same plcace in all cards

index.html
Fixed the submit button as there were duplicates
Fixes #34 
- index.html
=> fixed submit merge

assets/css/style.css, assets/js/script.js
The recipe card descriptions were not aligned similarly, now they are all the same. 
Fixes #56 
javascript and css
=> 56 re align descriptions in recipe cards

assets/js/details.js, assets/js/script.js, recipecards.html, recipedetails.html
Fixing the display for page 3, recipe details not loaded based on function. Also added second form to page 2.
Fixes #34 
=> added new js, worked w/ ethan on debugging for third page

assets/css/style.css, index.html
Got rid of the important by giving it a class.
Fixes #29 
- change
- change
- chage
=> got rid of the important for the theme

assets/css/style.css, assets/js/script.js, recipecards.html
fixed the margin issue.
Fixes #[issue]
css, line 193.
=> 59 add margin to the cards for the recipes

assets/css/style.css, assets/js/details.js, assets/js/script.js, recipedetails.html
=> 45 grab recipe id as a variable to pass on to the recipe detail page function

recipedetails.html
adds scrip code for script.js in details page
Fixes #65 
- go to first page change theme and then click through until in 3rd page
=> Fixes Theme page on details page

assets/js/details.js
sends you to a new tab when click view recipe instructions
Fixes #[issue]
showed team
=> View Recipe Instructions to take you to a new tab

assets/css/style.css, assets/js/script.js
=> 67 prevent recipe cards from collapsing in the middle size

assets/js/script.js
added new recipe api id 
Fixes #79 
- change
- change
- chage
=> added new appid and key for recipes

assets/css/style.css, assets/js/recipecards.js, assets/js/script.js, recipecards.html
Now the form on the second page aligns with the form selections from the first page.
Fixes #[issue]
recipecards.js
recipecards.html
=> 68 fix form options so you can also have a choice to select nothing

assets/js/details.js
added youtube api
Fixes #82 
- change
- change
- chage
=> added youtube api to details page

assets/js/script.js, index.html, recipecards.html
Solved merge conflicts and added extra options
Fixes #84 
- path/to/file
- change
- change
- chage
-assets/js/script.js
- index.html
=> 84 fix form page on page 2

recipecards.html, recipedetails.html
fixed header semantic and adds comments to html files, and deleted some duplicate code.
Fixes #80
-Look at code
=> 80 adding comments to the html code

recipecards.html
Fixes #[issue]
- path/to/file
- change
- change
- chage
=> fixed missing header closing tag

assets/css/style.css, assets/js/script.js, index.html, recipecards.html, recipedetails.html
Added javascript library animations
Fixes #35 
- index.html
=> added animations from 2 javascript libraries

assets/js/details.js, assets/js/script.js
finished adding comments to details.js and script.js
Fixes #92 
- open both js files after opening branch
=> 92 comments for details.js and script.js

assets/css/style.css
finished adding comments to the CSS file
Fixes #[issue]
- open css file on branch  or look below
=> Comments for Css

assets/css/style.css, recipedetails.html
Fixes #69 
-assets/css/style.css
- change
- chage
=> 69 theme color consistency and edits for fonts and minimal details
